2020/05/20 09:20:39 [crit] 6#6: *1 realpath() "/var/www/symfony/public" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2020/05/20 09:20:39 [error] 6#6: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9001", host: "localhost"
2020/05/20 09:20:42 [crit] 6#6: *1 realpath() "/var/www/symfony/public" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", host: "localhost", referrer: "http://localhost/"
2020/05/20 09:20:42 [error] 6#6: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.21.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.3:9001", host: "localhost", referrer: "http://localhost/"
2020/05/20 11:03:30 [crit] 6#6: *6 realpath() "/var/www/symfony/public" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET / HTTP/1.1", host: "localhost"
2020/05/20 11:03:30 [error] 6#6: *6 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9001", host: "localhost"
2020/05/25 10:52:12 [error] 7#7: *7 FastCGI sent in stderr: "PHP message: 2020-05-25T12:52:12+02:00 [critical] Uncaught Exception: Environment variable not found: "DATABASE_URL"" while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/25 10:55:24 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Missing = in the environment variable declaration in "/var/www/symfony/.env" at line 7.
...anther\n\nDATABASE_URL:"mysql://symfony:ro...
                        ^ line 7 offset 175 in /var/www/symfony/vendor/symfony/dotenv/Dotenv.php:498
Stack trace:
#0 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(235): Symfony\Component\Dotenv\Dotenv->createFormatException('Missing = in th...')
#1 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(190): Symfony\Component\Dotenv\Dotenv->lexVarname()
#2 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(508): Symfony\Component\Dotenv\Dotenv->parse('# define your e...', '/var/www/symfon...')
#3 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(60): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#4 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(80): Symfony\Component\Dotenv\Dotenv->load('/var/www/symfon...')
#5 /var/www/symfony/config/bootstrap.php(17): Symfony\Co" while reading response header from upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/25 10:55:47 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Missing = in the environment variable declaration in "/var/www/symfony/.env" at line 7.
...anther\n\nDATABASE_URL:"mysql://symfony:ro...
                        ^ line 7 offset 175 in /var/www/symfony/vendor/symfony/dotenv/Dotenv.php:498
Stack trace:
#0 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(235): Symfony\Component\Dotenv\Dotenv->createFormatException('Missing = in th...')
#1 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(190): Symfony\Component\Dotenv\Dotenv->lexVarname()
#2 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(508): Symfony\Component\Dotenv\Dotenv->parse('# define your e...', '/var/www/symfon...')
#3 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(60): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#4 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(80): Symfony\Component\Dotenv\Dotenv->load('/var/www/symfon...')
#5 /var/www/symfony/config/bootstrap.php(17): Symfony\Co" while reading response header from upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/25 10:55:49 [error] 7#7: *10 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Missing = in the environment variable declaration in "/var/www/symfony/.env" at line 7.
...anther\n\nDATABASE_URL:"mysql://symfony:ro...
                        ^ line 7 offset 175 in /var/www/symfony/vendor/symfony/dotenv/Dotenv.php:498
Stack trace:
#0 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(235): Symfony\Component\Dotenv\Dotenv->createFormatException('Missing = in th...')
#1 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(190): Symfony\Component\Dotenv\Dotenv->lexVarname()
#2 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(508): Symfony\Component\Dotenv\Dotenv->parse('# define your e...', '/var/www/symfon...')
#3 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(60): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#4 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(80): Symfony\Component\Dotenv\Dotenv->load('/var/www/symfon...')
#5 /var/www/symfony/config/bootstrap.php(17): Symfony\Co" while reading response header from upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/25 10:56:43 [error] 7#7: *17 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Dotenv\Exception\FormatException: Missing = in the environment variable declaration in "/var/www/symfony/.env" at line 7.
...anther\n\nDATABASE_URL:"mysql://symfony:ro...
                        ^ line 7 offset 175 in /var/www/symfony/vendor/symfony/dotenv/Dotenv.php:498
Stack trace:
#0 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(235): Symfony\Component\Dotenv\Dotenv->createFormatException('Missing = in th...')
#1 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(190): Symfony\Component\Dotenv\Dotenv->lexVarname()
#2 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(508): Symfony\Component\Dotenv\Dotenv->parse('# define your e...', '/var/www/symfon...')
#3 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(60): Symfony\Component\Dotenv\Dotenv->doLoad(false, Array)
#4 /var/www/symfony/vendor/symfony/dotenv/Dotenv.php(80): Symfony\Component\Dotenv\Dotenv->load('/var/www/symfon...')
#5 /var/www/symfony/config/bootstrap.php(17): Symfony\Co" while reading response header from upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 09:08:21 [crit] 6#6: *54 open() "/var/lib/nginx/tmp/fastcgi/1/00/0000000001" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 09:18:15 [crit] 6#6: *58 open() "/var/lib/nginx/tmp/fastcgi/2/00/0000000002" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 09:28:24 [error] 6#6: *69 FastCGI sent in stderr: "PHP message: 2020-05-26T11:28:24+02:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\CustomerController": argument "$customerService" of method "__construct()" references class "CustomerService" but no such service exists" while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 09:36:20 [error] 6#6: *72 FastCGI sent in stderr: "PHP message: 2020-05-26T11:36:20+02:00 [critical] Uncaught Exception: Expected to find class "App\Services\Customer\CustomerService" in file "/var/www/symfony/src/Services/Customer/CustomerService.php" while importing services from resource "../src/*", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/config/services.yaml (which is loaded in resource "/var/www/symfony/config/services.yaml")" while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 10:46:29 [error] 6#6: *122 FastCGI sent in stderr: "PHP message:" while reading response header from upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 11:50:52 [error] 6#6: *179 FastCGI sent in stderr: "PHP message: 2020-05-26T13:50:52+02:00 [critical] Uncaught Error: syntax error, unexpected ';'" while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 11:54:48 [error] 6#6: *190 FastCGI sent in stderr: "PHP message: 2020-05-26T13:54:48+02:00 [critical] Uncaught Exception: Cannot autowire service "App\Services\Customer\CustomerService": argument "$entityManager" of method "__construct()" references class "Doctrine\ORM\EntityManager" but no such service exists. Try changing the type-hint to "Doct" while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 11:54:48 [error] 6#6: *190 FastCGI sent in stderr: "rine\ORM\EntityManagerInterface" instead" while reading upstream, client: 172.23.0.1, server: , request: "POST /api/customer HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 14:05:53 [crit] 6#6: *221 open() "/var/lib/nginx/tmp/fastcgi/3/00/0000000003" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /api/customers HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 14:08:15 [crit] 6#6: *227 open() "/var/lib/nginx/tmp/fastcgi/4/00/0000000004" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /api/customers HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 14:08:58 [crit] 6#6: *230 open() "/var/lib/nginx/tmp/fastcgi/5/00/0000000005" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /api/customers HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 14:09:22 [crit] 6#6: *233 open() "/var/lib/nginx/tmp/fastcgi/6/00/0000000006" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /api/customers HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 14:10:11 [crit] 6#6: *236 open() "/var/lib/nginx/tmp/fastcgi/7/00/0000000007" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /api/customers HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 16:41:57 [error] 6#6: *288 FastCGI sent in stderr: "PHP message: 2020-05-26T18:41:57+02:00 [critical] Uncaught Exception: Expected to find class "App\Services\Customer\Exceptions\CustomerNotFoundException" in file "/var/www/symfony/src/Services/Customer/Exceptions/CustomerNotFoundException.php" while importing services from resource "../src/*", but it was not found! Check the namespace prefix used with the resource in /var/www/symfony/config/services.yaml (which is loaded in resource "/var/www/symfony/config/services.yaml")" while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 16:43:20 [crit] 6#6: *292 open() "/var/lib/nginx/tmp/fastcgi/8/00/0000000008" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/26 22:46:42 [crit] 6#6: *509 open() "/var/lib/nginx/tmp/fastcgi/9/00/0000000009" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
2020/05/27 10:21:26 [crit] 6#6: *1026 open() "/var/lib/nginx/tmp/fastcgi/0/01/0000000010" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET /_wdt/2d3341 HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost", referrer: "http://localhost/"
2020/05/27 12:37:16 [crit] 6#6: *1351 open() "/var/lib/nginx/tmp/fastcgi/1/01/0000000011" failed (13: Permission denied) while reading upstream, client: 172.23.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.3:9001", host: "localhost"
